### ISSUE TITLE
What about blank methods?

### ISSUE THREAD

**Issue by brunoocasali** [internetsistemas/guides#17]
The title says everything!

What about blank methods?

Reading [ruby-awesome](https://github.com/awesome/ruby-style-guide#source-code-layout) I find below this subtitle: _"One exception to the rule are empty-body methods."_

``` ruby
def show; end
```

instead of:

``` ruby
def show
end
```

Should be inside this guide: https://github.com/internetsistemas/guides/tree/master/style-guides/ruby

**Comment by felipefontoura** [comment]
Thanks @brunoocasali :+1: @gabrieljt what do you think?

**Comment by brunoocasali** [comment]
Oh, I forgot the label :|

**Comment by lcezermf** [comment]
Nice :+1: , I think the same about empty classes

``` ruby
class Customer; end
```

instead of

``` ruby
class Customer
end
```

**Comment by brunoocasali** [comment]
Yeah, I'm too @lccezinha not the version proposed for Ruby Awesome:

``` ruby
FooError = Class.new(StandardError)
```

I think about it how: "adding lot of complexity in nothing" kkkk 

Thanks!

**Comment by felipefontoura** [comment]
So far so good @brunoocasali!!

@lccezinha thanks for your comment ;)

**Comment by brunoocasali** [comment]
Thanks @felipefontoura and @lccezinha :+1:
