### ISSUE TITLE
Add Rubocop to follow ruby-style-guide

### ISSUE THREAD

**Issue by lcezermf** [internetsistemas/guides#20]
Hey guys, do you know this gem [Rubocop](https://github.com/bbatsov/rubocop) ?

It's a gem to check syntax error that are not following the ruby-guide, what do you think about add this gem in our projects, I think can be a good way to keep de code under de the guide.

**Comment by brunoocasali** [comment]
Hey I'm so exciting with this possibility :metal: 
@felipebroering @felipefontoura @gabrieljt what did you think about ?

**Comment by brunoocasali** [comment]
Hey guys what about this issue?! @internetsistemas/repense

**Comment by lcezermf** [comment]
Well I used this gem in another open source project, it was nice a easy to use.

Using it, we can focus on business rules and not worry so much about syntax, and guide problems in PR.

**Comment by vgsantoniazzi** [comment]
Rubocop is great tool, but a style-guide isn't good. I work on 4 projects and all these using different configuration files. One time configured, I think that is sufficient :+1:

**Comment by felipefontoura** [comment]
Hey @vgsantoniazzi! 

Do you have an example with these configs?

**Comment by felipefontoura** [comment]
Rubocop installed! Great too! :dancer:
