### ISSUE TITLE
Add about app/queries

### ISSUE THREAD

**Issue by brunoocasali** [internetsistemas/guides#25]
Write best practices about it!

**Comment by felipefontoura** [comment]
Hey @brunoocasali do you still think that it's a good idea?

**Comment by brunoocasali** [comment]
There are many organizations and projects using this pattern, but I don't know what can replace this kind of files, did you know any ?

**Comment by felipefontoura** [comment]
Nobody… Anyway I'll close this issue! Thanks @brunoocasali for your review.
